### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by afkLuna** [eddieqiii/tornado-user-example#1]
Hi I tried to run this program ang got an error at line 13. 
`    async def get(self):
            ^
SyntaxError: invalid syntax`

**Comment by eddieqiii** [comment]
Hey, are you using the right version of Python? I believe async functions of this form were only added in python 3.6.

**Comment by afkLuna** [comment]
> Hey, are you using the right version of Python? I believe async functions of this form were only added in python 3.6.

Thank you for the fast reply, turns out I was using python 2.7. It went fine after upgrading my python to 3.6. Thank youuu!
